# Generated by Django 4.1.3 on 2023-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planetas', '0001_initial'),
        ('personajes', '0001_initial'),
        ('especies', '0001_initial'),
        ('naves', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('episodio', models.CharField(max_length=2)),
                ('director', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField(verbose_name='fecha de lanzamiento')),
                ('especies', models.ManyToManyField(db_table='Pelicula_especie', to='especies.especie')),
                ('naves', models.ManyToManyField(db_table='Pelicula_nave', to='naves.nave')),
                ('personajes', models.ManyToManyField(db_table='Pelicula_personaje', to='personajes.personaje')),
                ('planetas', models.ManyToManyField(db_table='Pelicula_planeta', to='planetas.planeta')),
                ('vehiculos', models.ManyToManyField(db_table='Pelicula_vehiculo', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
                'db_table': 'Pelicula',
            },
        ),
    ]
