# Generated by Django 4.1.3 on 2023-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('diametro', models.IntegerField()),
                ('periodo_rotacion', models.IntegerField(verbose_name='periodo de rotación')),
                ('periodo_orbitacion', models.IntegerField(verbose_name='periodo de orbitación')),
                ('gravedad', models.CharField(max_length=50)),
                ('poblacion', models.IntegerField(verbose_name='población')),
            ],
            options={
                'verbose_name': 'planeta',
                'verbose_name_plural': 'planetas',
                'db_table': 'Planeta',
            },
        ),
    ]
