# Generated by Django 4.1.3 on 2023-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naves', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio_nacimiento', models.CharField(max_length=15, verbose_name='año de nacimiento')),
                ('genero', models.CharField(max_length=10, verbose_name='género')),
                ('planeta_nacimiento', models.CharField(max_length=50, verbose_name='planeta de nacimiento')),
                ('naves', models.ManyToManyField(db_table='Personaje_nave', to='naves.nave')),
                ('vehiculos', models.ManyToManyField(db_table='Personaje_vehiculo', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'personaje',
                'verbose_name_plural': 'personajes',
                'db_table': 'Personaje',
            },
        ),
    ]
